import { registerSW as registerViteSW } from 'virtual:pwa-register'

/**
 * Registers the PWA service worker (generated by vite-plugin-pwa).
 * Uses autoUpdate so users always get the latest build after refresh.
 */
export function registerSW() {
  if (!import.meta.env.PROD) return
  try {
    registerViteSW({
      immediate: true,
      onNeedRefresh() {
        window.location.reload()
      },
      onOfflineReady() {
        // App shell is cached and available offline
      },
    })
  } catch {
    // Service worker registration is optional — ignore failures
  }
}
